//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public int todo_id { get; set; }
        public string todo_content { get; set; }
    }
}
